version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb_projeto_joao
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example